spring.application.name=Project
spring.data.mongodb.uri=mongodb+srv://amanmangukiya02:wyetkNa9U7pZP6va@cluster0.oxktfdk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=placment
jwt.secret=YourSuperSecretKeyForJWT1234567890!@#
jwt.expiration=3600000
genai.api.url=https://openrouter.ai/api/v1/chat/completions
genai.api.key=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
