spring.application.name=Project
spring.data.mongodb.uri=mongodb+srv://amanmangukiya02:wyetkNa9U7pZP6va@cluster0.oxktfdk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=placment

jwt.secret=YourSuperSecretKeyForJWT1234567890!@#
jwt.expiration=3600000

spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.model=deepseek/deepseek-r1-distill-llama-70b


spring.main.web-application-type=servlet
spring.cloud.function.scan.enabled=false
