spring.application.name=Project
spring.data.mongodb.uri=mongodb+srv://amanmangukiya02:wyetkNa9U7pZP6va@cluster0.oxktfdk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=placment
jwt.secret=YourSuperSecretKeyForJWT1234567890!@#
jwt.expiration=3600000
genai.api.url=https://openrouter.ai/api/v1/chat/completions
genai.api.key=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
